suffering

diff --git a/.github/workflows/build_status.yml b/.github/workflows/build_status.yml
--- a/.github/workflows/build_status.yml
+++ b/.github/workflows/build_status.yml
@@ -1,39 +1,55 @@
 name: Build Status
 
 on:
-    push:
-        branches: [ '*' ]
-    pull_request:
+  push:
+    branches: [ '*' ]
+  pull_request:
 
 env:
-    JAVA_VERSION: 21
-    BUILD_NUMBER: ${{ github.run_number }}
+  JAVA_VERSION: 25
 
 jobs:
-    build:
-        runs-on: ubuntu-latest
-        steps:
-            -   uses: actions/checkout@v4
-            -   name: Set up JDK ${{ env.JAVA_VERSION }}
-                uses: actions/setup-java@v4
-                with:
-                    distribution: 'microsoft'
-                    java-version: ${{ env.JAVA_VERSION }}
-                    cache: 'gradle'
-            -   name: Validate Gradle Wrapper
-                uses: gradle/actions/wrapper-validation@v4
-            -   name: Grant execute permission for gradlew
-                run: chmod +x ./gradlew
-            -   name: Build with Gradle
-                run: ./gradlew build
-                env:
-                    GRADLE_BUILD_CACHE_USER: ${{ secrets.GRADLE_BUILD_CACHE_USER }}
-                    GRADLE_BUILD_CACHE_TOKEN: ${{ secrets.GRADLE_BUILD_CACHE_TOKEN }}
-            -   name: Upload build artifacts (Fabric)
-                continue-on-error: true
-                uses: actions/upload-artifact@v4
-                with:
-                    name: ${{ github.event.repository.name }}-Fabric-${{ github.sha }}
-                    path: |
-                        build/libs/*.jar
-                        !build/libs/*-dev.jar
+  build:
+    name: Build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
+      - name: Set up JDK ${{ env.JAVA_VERSION }}
+        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
+        with:
+          java-version: ${{ env.JAVA_VERSION }}
+          distribution: 'microsoft'
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
+      - name: Grant execute permission for gradlew
+        run: chmod +x ./gradlew
+      - name: Build with Gradle
+        run: ./gradlew assemble
+      - name: Upload build artifacts (Common)
+        continue-on-error: true
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        with:
+          name: ${{ github.event.repository.name }}-Common-${{ github.sha }}
+          path: |
+            Common/build/libs/*.jar
+      - name: Upload build artifacts (Fabric)
+        continue-on-error: true
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        with:
+          name: ${{ github.event.repository.name }}-Fabric-${{ github.sha }}
+          path: |
+            Fabric/build/libs/*.jar
+      - name: Upload build artifacts (NeoForge)
+        continue-on-error: true
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        with:
+          name: ${{ github.event.repository.name }}-NeoForge-${{ github.sha }}
+          path: |
+            NeoForge/build/libs/*.jar
+      - name: Run tests
+        run: ./gradlew check
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@d9f48fc87bc235f7e214acf696ca5abc0a986f16 # v6.4.2
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
